/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ApartmentOutlined: typeof import('@ant-design/icons-vue')['ApartmentOutlined']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArrowRightOutlined: typeof import('@ant-design/icons-vue')['ArrowRightOutlined']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Cell: typeof import('./src/components/Cell.vue')['default']
    ComponentTitle: typeof import('./src/components/ComponentTitle.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm.vue')['default']
    LocaleDropdown: typeof import('./src/components/LocaleDropdown.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    ShopOutlined: typeof import('@ant-design/icons-vue')['ShopOutlined']
    TableText: typeof import('./src/components/TableText.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WalletOutlined: typeof import('@ant-design/icons-vue')['WalletOutlined']
  }
}
